"""Add GradeKanji model

Revision ID: 04f6311a912a
Revises: 474d0520b3a3
Create Date: 2025-12-23 16:22:10.596305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f6311a912a'
down_revision = '474d0520b3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_kanji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kanji', sa.String(length=1), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('on_reading', sa.String(length=100), nullable=True),
    sa.Column('kun_reading', sa.String(length=100), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=True),
    sa.Column('meaning', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kanji')
    )
    with op.batch_alter_table('grade_kanji', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_kanji_grade'), ['grade'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_kanji', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_kanji_grade'))

    op.drop_table('grade_kanji')
    # ### end Alembic commands ###
